defmodule Tipay.UserTicketTokens.EventHandlers.User do
  alias Tipay.Users.Events.UserSubscriber
  alias Tipay.Users.Events.UserCreated
  alias Tipay.UserTicketTokens.UserTicketToken
  alias Tipay.UserTicketTokens

  @behaviour UserSubscriber

  @impl UserSubscriber
  def user_created(%UserCreated{user_id: user_id}) do
    result =
      UserTicketTokens.create_user_token(%{
        name: "autogenerated",
        user_id: user_id
      })

    case result do
      {:ok, %UserTicketToken{}} -> :ok
      error -> error
    end
  end
end
